# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Boba Thoughts
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/formatting@v2

  images:
    name: images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/images@v2
        with:
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


  e2e_testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./.next

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          project: ./
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:3000"

  component_testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./.next

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          component: true
          project: ./
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:3000"
